### ISSUE TITLE
Posts aren't updating anymore

### ISSUE THREAD

**Issue by antstorm** [goddamnyouryan/coven-api#10]
Hi,

I've noticed that posts have stopped updating 9 days ago, which seems to be the problem with the server because `rake posts:sync` from repo works. @goddamnyouryan can you please have a look?

Thank you!

**Comment by goddamnyouryan** [comment]
Hmm, something seemingly with delayed jobs on heroku free maybe? I made it so that it no longer uses delayed jobs and instead just fetches new posts in the worker instance. Let me know if it continues to not update.

**Comment by antstorm** [comment]
It is updating now, thank you!
