### ISSUE TITLE
Upgrade to Ruby 2.6.3

### ISSUE THREAD

**Issue by tancnle** [goddamnyouryan/coven-api#11]
## Description

Upgrade to modern Ruby version 2.6.3.

**Comment by goddamnyouryan** [comment]
@tancnle I don't have time to handle this at the moment but you are definitely welcome to submit a pull request for it and I will merge it.

**Comment by tancnle** [comment]
@goddamnyouryan Yep I am working on an upgrade branch now. I will check in later, there are potential changes around heroku support since they have removed support for some of the gems (i.e. `heroku`/`workless`). Would it be possible to understand a bit on how the prod deployment work?
