### ISSUE TITLE
Does coven.link have a public API?

### ISSUE THREAD

**Issue by jackyliang** [goddamnyouryan/coven-api#5]
This isn't an issue per se, and more of a question.

Does coven.link have a public API one can access? I'm planning on write a command line tool to display `coven.link` aggregated news.

**Comment by goddamnyouryan** [comment]
@jackyliang sure does: it's hosted at http://api.coven.link/api/v1/posts

**Comment by jackyliang** [comment]
@goddamnyouryan You just made my week... I know what project I'm working on next.

**Comment by goddamnyouryan** [comment]
@jackyliang awesome! Let me know if you need any help. Feel free to customize the api too as you see fit.

**Comment by jackyliang** [comment]
@goddamnyouryan I love `coven.link`! Do you have any limits on how many times I should ping the site?

**Comment by goddamnyouryan** [comment]
@jackyliang ha nope. Though it only updates every 10 minutes so you might want to just re-sync every 10 minutes? I should probably get some basic caching set up on the endpoint, maybe just some memcached or something like that.

**Comment by jackyliang** [comment]
That would be good! Perhaps a way to know in the API when it was last refreshed so my cli app could synchronize with you (I can cache too)?

**Comment by goddamnyouryan** [comment]
@jackyliang that could work. I think for now just develop with it as is, then we can add memcached as needed, and then a synced_at if we eventually need local caching on your end.
