### ISSUE TITLE
Wrong links in README

### ISSUE THREAD

**Issue by jackyliang** [goddamnyouryan/coven-api#7]
Check out the [Coven Command Line app](https://www.github.com/goddamnyouryan/coven-api), built in php by [jackyliang](https://github.com/jackyliang).

Should be:

    Check out the [Coven Command Line app](https://github.com/jackyliang/coven-cli), built in php by [jackyliang](https://github.com/jackyliang).

In both `coven-api` and `coven`.

**Comment by goddamnyouryan** [comment]
@jackyliang whoops, good catch. Fixed!
